CREATE USER vanilla PASSWORD 'script' SUPERUSER CREATEDB;
CREATE TABLESPACE tbs LOCATION '/home/tbs';
CREATE DATABASE mozilla OWNER 'vanilla' ENCODING 'UTF-8' TABLESPACE tbs;
-- LC_COLLATE 'ko_KR.utf8' LC_CTYPE 'ko_KR.utf8'