CREATE TABLE NMUser (
	OID text PRIMARY KEY,
	ACCOUNT varchar(32) UNIQUE,
	PWD varchar(1000) NOT NULL,
	EMAIL varchar(256),
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE timestamp,
	NICKNAME varchar(16),
	SEX char(1) NOT NULL DEFAULT 'N',
	IS_DELETE boolean NOT NULL DEFAULT FALSE
);

CREATE TABLE NMAccountBook (
	OID text PRIMARY KEY,
	USER_OID text NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE timestamp,
	TARGET_DATE timestamp NOT NULL,
	DESCRIPTION varchar(1000),
	INCOME numeric(15, 5) NOT NULL,
	OUTCOME numeric(15, 5) NOT NULL,
	ORDER integer,
	IS_DELETE boolean NOT NULL DEFAULT FALSE
);

CREATE TABLE NMTag (
	OID text PRIMARY KEY,
	NAME varchar(32) NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE timestamp,
	TARGET_TYPE varchar(4) NOT NULL,
	TARGET_OID text NOT NULL,
	IS_DELETE boolean NOT NULL DEFAULT FALSE
);

CREATE TABLE NMHistory (
	OID text PRIMARY KEY,
	USER_OID text NOT NULL,
	ACTION_TYPE varchar(8) NOT NULL,
	TARGET_TYPE varchar(4) NOT NULL,
	TARGET_OID text NOT NULL
);

CREATE TABLE NMConfig (
	OID text PRIMARY KEY,
	NAME varchar(128) UNIQUE,
	VALUE varchar(1024),
	DESCRIPTION varchar(256),
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE timestamp,
	IS_ENABLE boolean NOT NULL DEFAULT FALSE,
	IS_DELETE boolean NOT NULL DEFAULT FALSE
);

CREATE TABLE NMSignUpRequest (
	OID text PRIMARY KEY,
	EMAIL varchar(256) NOT NULL,
	CODE varchar(1024),
	EXPIRED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	IS_EXPIRED boolean NOT NULL DEFAULT FALSE
);

ALTER TABLE NMHistory ADD FOREIGN KEY (USER_OID) REFERENCES NMUser (OID);
ALTER TABLE NMHistory ADD FOREIGN KEY (TARGET_OID) REFERENCES NMUser (OID);
ALTER TABLE NMAccountBook ADD FOREIGN KEY (USER_OID) REFERENCES NMUser (OID);
ALTER TABLE NMAccountBook_NMHistory ADD FOREIGN KEY (NMAccountBook_OID) REFERENCES NMAccountBook (OID);
ALTER TABLE NMAccountBook_NMHistory ADD FOREIGN KEY (NMHistory_TARGET_OID) REFERENCES NMHistory (TARGET_OID);
ALTER TABLE NMAccountBook_NMTag ADD FOREIGN KEY (NMAccountBook_OID) REFERENCES NMAccountBook (OID);
ALTER TABLE NMAccountBook_NMTag ADD FOREIGN KEY (NMTag_TARGET_OID) REFERENCES NMTag (TARGET_OID);
ALTER TABLE NMTag_NMHistory ADD FOREIGN KEY (NMTag_OID) REFERENCES NMTag (OID);
ALTER TABLE NMTag_NMHistory ADD FOREIGN KEY (NMHistory_TARGET_OID) REFERENCES NMHistory (TARGET_OID);

INSERT INTO NMUser (OID, ACCOUNT, PWD, NICKNAME) VALUES ('admin', 'admin', 'admin', 'admin');
